[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/watch"
  to = "/.netlify/functions/og"
  status = 200
  force = true
  conditions = {Bot = true}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
